### ISSUE TITLE
Gulp error

### ISSUE THREAD

**Issue by olivierbossel** [ryanbahniuk/babel-plugin-dataset#1]
Hi man,

First of all, thanks for your work, it seams very useful.
Unfortunately I try to use your plugin un my gulp babel based project and I not able to make it work.

my configuration is this :

``` coffee
# build the package
gulp.task 'webpack', ->
    gulp.src './coffee/**/*.coffee'
    .pipe gulpWebpack webpackParams
    .pipe babel
        presets: ['es2015']
        plugins: ['dataset']
    # .pipe uglify()
    .pipe gulp.dest 'js'
```

And I get this error when I compile

```
Error: Cannot find module 'datasetUtilities'
```

Have you an idea why?

Thanks in advance!

Cheers!

**Comment by ryanbahniuk** [comment]
Hey @olivierbossel, thanks for the bug catch. I think I know the problem, but the larger issue is that this project is a WIP and probably shouldn't be used at this point. It works for one use case of dataset (accessing it like element.dataset.key directly), but not for the use case of passing the dataset object around once it is assigned to a variable. After a brief exploration into solving that problem, I stopped working on this and decided not to publish to npm until there was a more complete solution.

**Comment by olivierbossel** [comment]
Hi,

Thanks for your answer. I can understand that it's quite hard to cover all the case.
For now I've written my own little js method to access the dataset safely. I will continue with that for now and hoping that people put their .... old IE up in the ass :)

Thanks again!

Cheers!
